baseURL = "https://people.hotdogsandeggs.com/"
languageCode = "en-us"
title = "Chris Gallo | What They Said"
[permalinks]
    posts = ":slug"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]

    author = "Chris Gallo"
    description = "You're reading What They Said, a project by Chris Gallo since 2014."
