# ==========================
# == Jekyll Configuration ==
# ==========================
markdown: rdiscount
permalink: :title

# ==========================
# == Custom Configuration ==
# ==========================

title: People | Hot Dogs and Eggs
subtitle: "The website of Chris Gallo."
url: http://hotdogsandeggs.com/
description: "You can see a lot just by listening. Transcribed advice from real people."
navigation:
 - title: About
   url: /about/
 - title: Blog
   url: http://blog.hotdogsandeggs.com/
 - title: Say hi
   url: /about/#contact