# ==========================
# == Jekyll Configuration ==
# ==========================
markdown: kramdown
permalink: :title


# ==========================
# == Custom Configuration ==
# ==========================
title: People | Hot Dogs and Eggs
subtitle: "The website of Chris Gallo."
url: http://people.hotdogsandeggs.com
description: "You can see a lot just by listening. Transcribed advice from real people."
twitter_username: cjgallo
navigation:
 - title: Blog
   url: http://blog.hotdogsandeggs.com/
 - title: People
   url: /
