# ==========================
# == Jekyll Configuration ==
# ==========================
markdown: kramdown
permalink: :title


# ==========================
# == Custom Configuration ==
# ==========================
title: People | Hot Dogs and Eggs
subtitle: "The website of Chris Gallo."
url: https://people.hotdogsandeggs.com
description: "You can see a lot just by listening. Transcribed advice from real people by Chris Gallo."
twitter_username: cjgallo
navigation:
 - title: Home
   url: https://hotdogsandeggs.com/ 
 - title: Blog
   url: https://blog.hotdogsandeggs.com/
